repos:
# python
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.265
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: https://github.com/datarootsio/databooks
    rev: 1.3.7
    hooks:
    -   id: databooks-meta
# sql
-   repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.1.0
    hooks:
    -   id: sqlfluff-fix
# mostly web stuff
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.9-for-vscode
    hooks:
    -   id: prettier
        types_or: [css, javascript, scss, html, vue, jsx]
# misc
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: detect-private-key
    -   id: check-json
    -   id: check-toml
    -   id: check-xml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: check-docstring-first
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.3
    hooks:
    -   id: gitleaks
-   repo: https://github.com/commitizen-tools/commitizen
    rev: 3.2.1
    hooks:
        -   id: commitizen
            stages: [commit-msg]
