OPT_TOKENS = {
    "anli": [
        ("<hyp1>", "</hyp1>"),
        ("<hyp2>", "</hyp2>"),
    ],
    "cosmosqa": [
        ("<answer0>", "</answer0>"),
        ("<answer1>", "</answer1>"),
        ("<answer2>", "</answer2>"),
        ("<answer3>", "</answer3>"),
    ],
    "hellaswag": [
        ("<ending_options 0>", "</ending_options 0>"),
        ("<ending_options 1>", "</ending_options 1>"),
        ("<ending_options 2>", "</ending_options 2>"),
        ("<ending_options 3>", "</ending_options 3>"),
    ],
    "physicaliqa": [
        ("<sol1>", "</sol1>"),
        ("<sol2>", "</sol2>"),
    ],
    "socialiqa": [
        ("<answerA>", "</answerA>"),
        ("<answerB>", "</answerB>"),
        ("<answerC>", "</answerC>"),
    ],
    "winogrande": [
        ("<option1>", "</option1>"),
        ("<option2>", "</option2>"),
    ],
    "mtl_semcor": [
        ("<g>", "</g>"),
    ],
}

ALL_TOKENS = {
    "anli": [
        "<obs1>",
        "</obs1>",
        "<obs2>",
        "</obs2>",
        OPT_TOKENS["anli"][0][0],
        OPT_TOKENS["anli"][0][1],
        OPT_TOKENS["anli"][1][0],
        OPT_TOKENS["anli"][1][1],
    ],
    "cosmosqa": [
        "<context>",
        "</context>",
        "<question>",
        "</question>",
        OPT_TOKENS["cosmosqa"][0][0],
        OPT_TOKENS["cosmosqa"][0][1],
        OPT_TOKENS["cosmosqa"][1][0],
        OPT_TOKENS["cosmosqa"][1][1],
        OPT_TOKENS["cosmosqa"][2][0],
        OPT_TOKENS["cosmosqa"][2][1],
        OPT_TOKENS["cosmosqa"][3][0],
        OPT_TOKENS["cosmosqa"][3][1],
    ],
    "hellaswag": [
        "<ctx>",
        "</ctx>",
        OPT_TOKENS["hellaswag"][0][0],
        OPT_TOKENS["hellaswag"][0][1],
        OPT_TOKENS["hellaswag"][1][0],
        OPT_TOKENS["hellaswag"][1][1],
        OPT_TOKENS["hellaswag"][2][0],
        OPT_TOKENS["hellaswag"][2][1],
        OPT_TOKENS["hellaswag"][3][0],
        OPT_TOKENS["hellaswag"][3][1],
    ],
    "physicaliqa": [
        "<goal>",
        "</goal>",
        OPT_TOKENS["physicaliqa"][0][0],
        OPT_TOKENS["physicaliqa"][0][1],
        OPT_TOKENS["physicaliqa"][1][0],
        OPT_TOKENS["physicaliqa"][1][1],
    ],
    "socialiqa": [
        "<context>",
        "</context>",
        "<question>",
        "</question>",
        OPT_TOKENS["socialiqa"][0][0],
        OPT_TOKENS["socialiqa"][0][1],
        OPT_TOKENS["socialiqa"][1][0],
        OPT_TOKENS["socialiqa"][1][1],
        OPT_TOKENS["socialiqa"][2][0],
        OPT_TOKENS["socialiqa"][2][1],
    ],
    "winogrande": [
        "<sentence>",
        "</sentence>",
        OPT_TOKENS["winogrande"][0][0],
        OPT_TOKENS["winogrande"][0][1],
        OPT_TOKENS["winogrande"][1][0],
        OPT_TOKENS["winogrande"][1][1],
    ],
    "mtl_semcor": [
        "<classify>",
        "</classify>",
        OPT_TOKENS["mtl_semcor"][0][0],
        OPT_TOKENS["mtl_semcor"][0][1],
    ],
}
